In [1]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori
TFI = pd.read_csv("transfer.csv")
tfi_list = np.unique(TFI["trans_id"])
TFI.sort_values(by=["clnt_id","trans_id"])

clnt_id  trans_id  trans_seq biz_unit  pd_c     de_dt  de_tm  buy_am  \
558694        2     42449          1      A02  1015  20190704  15:34   46430   
110423        2     62037          1      A03    92  20190729  23:47   36000   
103283        2     64691          5      A03    92  20190731  21:25    1800   
103337        2     64691          2      A03   151  20190731  21:25    3990   
109189        2     64691          3      A03   351  20190731  21:25    4690   
...         ...       ...        ...      ...   ...       ...    ...     ...   
474634    72424    136596          1      B01   392  20190727  11:22    5980   
474645    72424    136596         35      B01  1587  20190727  11:22    1280   
474728    72424    136596         20      B01   862  20190727  11:22    2000   
474729    72424    136596         14      B01  1189  20190727  11:22    3960   
474892    72424    136596         22      B01   862  20190727  11:22    2000   

        buy_ct  
558694       1  
110423      20  
103283       1  
103337       1  
109189       1  
...        ...  
474634       1  
474645       1  
474728       1  
474729       2  
474892       2  

[573867 rows x 9 columns]

array([1, 2, 3, 4])

In [2]:
tfi1 = TFI[["trans_id","pd_c"]]
buy_list = []
for i in tfi_list:
    tfis = tfi1[tfi1["trans_id"]==i]
    if tfis.shape[0]==1:
        continue
    a= []
    for j in tfis["pd_c"]:
        a.append(j)
    a = np.unique(a)
    buy_list.append(a)


In [16]:
buy_list

[array([ 388,  548,  894,  897, 1447, 1529]),
 array([ 111,  542,  894, 1447]),
 array([152, 191, 198, 352, 388, 405, 526, 542]),
 array([ 388,  894,  897, 1447, 1529]),
 array([ 951,  961, 1015, 1213]),
 array([ 182,  192,  395,  540,  542,  938,  990, 1143, 1216, 1383]),
 array([  97,  182,  188,  192,  194,  410,  516,  797,  996, 1189, 1393]),
 array([  70,  107,  182,  565, 1447]),
 array([ 547,  567, 1210, 1235, 1258, 1571]),
 array([ 178,  379,  382,  917,  996, 1570, 1597]),
 array([ 114,  194,  353,  897,  964,  996, 1182, 1183, 1628]),
 array([  27,  175,  348,  374,  525,  547,  565,  938, 1278, 1447, 1617]),
 array([  66,  581, 1447, 1578]),
 array([ 107,  182,  565, 1447]),
 array([547, 964]),
 array([ 194,  349,  350,  567,  704, 1393, 1447]),
 array([ 348,  539,  964,  999, 1015]),
 array([348, 567, 581, 965]),
 array([ 172,  205,  348,  409,  565, 1174, 1393, 1501, 1617]),
 array([ 344,  515,  565,  883,  889, 1216, 1425, 1447, 1571]),
 array([ 565, 1447]),
 array([347,

In [3]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(buy_list).transform(buy_list)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [4]:
from mlxtend.frequent_patterns import association_rules
frequent_itemsets = apriori(df, min_support=0.01, use_colnames=True)
frequent_itemsets.sort_values(by="support")

support      itemsets
205  0.010004   (1395, 515)
196  0.010017   (354, 1183)
222  0.010017  (1184, 1183)
7    0.010118         (110)
207  0.010131   (1395, 516)
..        ...           ...
31   0.123448         (221)
144  0.124032        (1617)
98   0.130367        (1213)
83   0.136791         (964)
34   0.148648         (347)

[246 rows x 2 columns]

In [5]:
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2).sort_values(by="lift",ascending=False)

antecedents consequents  antecedent support  consequent support   support  \
33       (893)       (897)            0.052964            0.038174  0.014599   
32       (897)       (893)            0.038174            0.052964  0.014599   
53      (1215)      (1210)            0.049981            0.071296  0.014295   
52      (1210)      (1215)            0.071296            0.049981  0.014295   
42      (1184)      (1183)            0.040053            0.064187  0.010017   
..         ...         ...                 ...                 ...       ...   
1        (188)       (347)            0.055364            0.148648  0.011591   
22      (1616)       (347)            0.059121            0.148648  0.012213   
21      (1395)       (347)            0.112200            0.148648  0.023093   
18      (1183)       (347)            0.064187            0.148648  0.012987   
4        (194)       (347)            0.063730            0.148648  0.012835   

    confidence      lift  leverage  conviction  
33    0.275647  7.220728  0.012578    1.327841  
32    0.382441  7.220728  0.012578    1.533514  
53    0.286005  4.011499  0.010731    1.300714  
52    0.200499  4.011499  0.010731    1.188264  
42    0.250079  3.896112  0.007446    1.247883  
..         ...       ...       ...         ...  
1     0.209356  1.408399  0.003361    1.076783  
22    0.206571  1.389664  0.003424    1.073003  
21    0.205816  1.384585  0.006414    1.071983  
18    0.202334  1.361161  0.003446    1.067304  
4     0.201394  1.354841  0.003362    1.066048  

[66 rows x 9 columns]

In [ ]:
OAI = pd.read_csv("Online.csv")
oai0 = OAI[OAI["action_type"]==0].reset_index(drop=True)
oai0[["clnt_id","sess_id"]] = oai0[["clnt_id","sess_id"]].astype(str)
oai0["oai_list"] = oai0["clnt_id"]+"_"+ oai0["sess_id"]
oai0.shape

In [7]:
oai_list = np.unique(oai0["oai_list"])
oai1 = oai0[["oai_list","sech_kwd"]]
sech_list = []
for i in oai_list:
    oais = oai1[oai1["oai_list"]==i]
    if oais.shape[0]==1:
        continue
    a= []
    for j in oais["sech_kwd"]:
        a.append(j)
    a = np.unique(a)
    sech_list.append(a)

In [ ]:
oai2 = oai1["sech_kwd"].value_counts()
oai2=oai2[oai2 < 3]
for i in oai2.index:
    oai1.drop(oai1[oai1["sech_kwd"]==i].index)
oai1.shape

In [15]:
sech_list

[array(['단화', '수페르가'], dtype='<U4'),
 array(['가브리살', '매일요거트', '복숭아', '요구르트', '요플레', '황도', '황도복숭아'], dtype='<U5'),
 array(['슬랙스', '한우구이세트', '한우구이세트 스마트픽'], dtype='<U11'),
 array(['가열식 가습기', '가열식가습기'], dtype='<U7'),
 array(['LBL', 'LBL구스', 'LBL캐시미어코트', '이월상품'], dtype='<U9'),
 array(['LB18FWWLC0002', 'LB18FWWLC0002PPP066', '마리타 후리나이넨',
        '캐시미어100뉴베네타롱코트'], dtype='<U19'),
 array(['LBL캐시미어코트'], dtype='<U9'),
 array(['모슬린 프리츠 팬츠', '모슬린 플리츠'], dtype='<U10'),
 array(['로아앤제인', '앱에서 쓰는 쇼핑 지원금'], dtype='<U13'),
 array(['해지스맨 티셔츠', '해지스맨 티셔츠 윔블던'], dtype='<U12'),
 array(['쌀', '쌀 10KG 이천', '쌀 20KG', '쌀 20KG 이천'], dtype='<U9'),
 array(['위니아제습기', '제습기'], dtype='<U6'),
 array(['필립스 소닉케어 다이아몬드', '필립스 소닉케어 다이아몬드 칫솔모', '필립스 소닉케어 칫솔모'],
       dtype='<U18'),
 array(['네모탭', '필립스 칫솔모'], dtype='<U7'),
 array(['브라운 전동 칫솔', '브라운 칫솔'], dtype='<U9'),
 array(['지오다노'], dtype='<U4'),
 array(['겐조', '겐조키즈'], dtype='<U4'),
 array(['에버랜드'], dtype='<U4'),
 array(['소마덤'], dtype='<U3'),
 array(['골전도'], dtype='<U3'),

In [16]:
te1 = TransactionEncoder()
te_ary1 = te1.fit(sech_list).transform(sech_list)
df1 = pd.DataFrame(te_ary1, columns=te.columns_)

MemoryError: 

In [11]:
frequent_sechsets = apriori(df1, min_support=0.01, use_colnames=True)
frequent_sechsets.sort_values(by="support")

IndexError: tuple index out of range

In [17]:
df1

!베이컨      "  "5218KD417  "EF-ZG977 48  "GRN 현아  "JJ지고트   \
0       False  False       False         False    False    False   
1       False  False       False         False    False    False   
2       False  False       False         False    False    False   
3       False  False       False         False    False    False   
4       False  False       False         False    False    False   
...       ...    ...         ...           ...      ...      ...   
102781  False  False       False         False    False    False   
102782  False  False       False         False    False    False   
102783  False  False       False         False    False    False   
102784  False  False       False         False    False    False   
102785  False  False       False         False    False    False   

        "PWX Q418-2576  "[프롤린유산균] 종근당건강 락토핏 생유산균 코어 (2    "am  \
0                False                           False  False   
1                False                           False  False   
2                False                           False  False   
3                False                           False  False   
4                False                           False  False   
...                ...                             ...    ...   
102781           False                           False  False   
102782           False                           False  False   
102783           False                           False  False   
102784           False                           False  False   
102785           False                           False  False   

        "javascript:fn_goodsCheckAdult({goods_no:592584113  ...     힙업  힙업 운동  \
0                                                   False   ...  False  False   
1                                                   False   ...  False  False   
2                                                   False   ...  False  False   
3                                                   False   ...  False  False   
4                                                   False   ...  False  False   
...                                                   ...   ...    ...    ...   
102781                                              False   ...  False  False   
102782                                              False   ...  False  False   
102783                                              False   ...  False  False   
102784                                              False   ...  False  False   
102785                                              False   ...  False  False   

         힙합바지    힛리얼    힛케잌  （디마오떼피자  （주오뚜기    �곗샂    �뚰깢    �쒖옣  
0       False  False  False    False  False  False  False  False  
1       False  False  False    False  False  False  False  False  
2       False  False  False    False  False  False  False  False  
3       False  False  False    False  False  False  False  False  
4       False  False  False    False  False  False  False  False  
...       ...    ...    ...      ...    ...    ...    ...    ...  
102781  False  False  False    False  False  False  False  False  
102782  False  False  False    False  False  False  False  False  
102783  False  False  False    False  False  False  False  False  
102784  False  False  False    False  False  False  False  False  
102785  False  False  False    False  False  False  False  False  

[102786 rows x 90731 columns]